Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Машина 1: Nginx на порту 82
  config.vm.define "web" do |web|
    web.vm.network "public_network"
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
      sed -i 's/listen 80/listen 80/g' /etc/nginx/sites-available/default
      mkdir -p /home/vagrant/.ssh
      echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIP7LrSQI76YNmNF6QVAH6jsKQnDPiAA4fV7YaJtbPxV" >> /home/vagrant/.ssh/authorized_keys
      systemctl restart nginx
    SHELL
  end


 end
end