Vagrant.configure("2") do |config|
  # Указываем образ Ubuntu
  config.vm.box = "ubuntu/focal64"

  # Настройка сети (публичный IP)
  config.vm.network "public_network"

  # Установка Nginx и замена порта 80 на 82
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    sed -i 's/listen 80 default_server;/listen 82 default_server;/g' /etc/nginx/sites-available/default
    sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:82 default_server;/g' /etc/nginx/sites-available/default
    systemctl restart nginx
  SHELL
end